services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    command: start-dev --log="console,file" --log-console-level=info --log-file="/opt/keycloak/logs/keycloak.log"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: DEBUG
    ports:
      - target: 8080    # container port
        published: 8081 # host port
        protocol: tcp
        mode: host
    volumes:
      - ./data:/opt/keycloak/data/h2
      - ./logs:/opt/keycloak/logs
